version: "3.5"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dashbook
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: -p 5432

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  # pgadmin:
